### ISSUE TITLE
Questions about the Proposition A.1

### ISSUE THREAD

**Issue by karenyun** [yuhui-zh15/drml#1]
Hi,

Thanks for your excellent work. 
I have some questions. Would you like to give me some indications?
1) `E_(x)[x-x^(T)g^(')g^(')]`, why you use this term as the center of x, is there exist a geometric meaning?
2) In Proposition A.1, you suppose that gap g is orthogonal to the span of image features, and image features have zero means in the subspace orthogonal to g, why do you explain that it is the projected x in the subspace orthogonal to g? I am confused about that. why there is a projection rather than the original x as you supposed?

**Comment by yuhui-zh15** [comment]
Hi @karenyun,

Thank you for your interest in our work. 

1.  [x^(T)g^(')]g^(') is the projection of vector x on the gap direction g (https://en.wikipedia.org/wiki/Vector_projection), so x -  [x^(T)g^(')]g^(') is the projection of vector x in the subspace orthogonal to g, which is \Pi_g(x) in Proposition A.1. Basically, we hope to verify "image features have zero means in the subspace orthogonal to g" from this statistic.

2. We use the projection \Pi_g(x) rather than original x because it is derived from the theory. Check the last line in the equation, we need a condition E[\Pi_g(x)] = \vec 0 to reduce the first term to \tau Wg.

Hope this helps!

**Comment by karenyun** [comment]
Hi @yuhui-zh15 ,

Thanks for you quick reply!

For 1), can I say original image features are not orthogonal to g? If yes, why do you suppose "g is orthogonal to the span of image features" in Proposition A.1?

I still have another question, whether you base on the g is a constant vector, so by using x-E_(x)[x], y-E_(y)[y] in cross-modal transfer training to allow the modality gap to be zero? 

Thanks very much!

**Comment by yuhui-zh15** [comment]
1) Correct. That is why we decompose x into two parts in Proposition 1: x = \tau g + Pi_g (x)

2) Correct. With this method, gap becomes zero: (x - Ex) - (y - Ey) = (x - y) - (Ex - Ey)= g - g = 0
